import datetime
versionNumberText = 'v. 0.5'
copyrightString = '© ' + datetime.date.today().strftime("%Y") + ' Biserica Adventistă de Ziua a Șaptea "Speranța" Cluj-Napoca'
windowTitleText = 'Lower Thirds Generator'
nameText = 'Name:'
familyNameText = 'Family Name:'
titleText = 'Subtitle (optional):'
generateButtonText = 'Generate Image'
clearInputButtonText = 'Clear Input Text'
clearOutputFolderButtonText = 'Clear Output Folder'
contactUsText = 'Contact Us'
settingsText = 'Settings'
helpText = 'Help'
numberOfFilesText = 'Number of outputs:'
confirmationText = 'New lower thirds was created for: '

settingsTitleText = 'Settings'
nameFontSizeText = 'Font size for name:'
namePositionXText = 'X Coordinate for name:'
namePositionYText = 'Y Coordinate for name:'
titleFontSizeText = 'Font size for title:'
titlePositionXText = 'X Coordinate for title:'
titlePositionYText = 'Y Coordinate for title:'
saveButtonText = 'Save'
defaultButtonText = 'Defaults'